{
    "report_meta": {
        "scan_target": "files",
        "scanned": [
            "requirements.txt"
        ],
        "policy_file": null,
        "policy_file_source": "local",
        "api_key": false,
        "local_database_path": null,
        "safety_version": "2.3.5",
        "timestamp": "2023-04-20 17:51:33",
        "packages_found": 14,
        "vulnerabilities_found": 3,
        "vulnerabilities_ignored": 0,
        "remediations_recommended": 0,
        "telemetry": {
            "os_type": "Windows",
            "os_release": "10",
            "os_description": "Windows-10-10.0.22621-SP0",
            "python_version": "3.9.12",
            "safety_command": "check",
            "safety_options": {
                "files": {
                    "-r": 1
                },
                "output": {
                    "--output": 1
                }
            },
            "safety_version": "2.3.5",
            "safety_source": "cli"
        },
        "git": {
            "branch": "master",
            "tag": "",
            "commit": "384c0cac795023c067de58a5e3cfd282c8d74751",
            "dirty": true,
            "origin": "https://github.com/Ganesh-P03/SE_tool_team5.git"
        },
        "project": null,
        "json_version": 1
    },
    "scanned_packages": {
        "fastapi": {
            "name": "fastapi",
            "version": "0.92.0"
        },
        "pydantic": {
            "name": "pydantic",
            "version": "1.10.5"
        },
        "typingextensions": {
            "name": "typingextensions",
            "version": "4.5.0"
        },
        "starlette": {
            "name": "starlette",
            "version": "0.25.0"
        },
        "anyio": {
            "name": "anyio",
            "version": "3.6.2"
        },
        "idna": {
            "name": "idna",
            "version": "3.4"
        },
        "sniffio": {
            "name": "sniffio",
            "version": "1.3.0"
        },
        "numpy": {
            "name": "numpy",
            "version": "1.21.5"
        },
        "ratelimit": {
            "name": "ratelimit",
            "version": "2.2.1"
        },
        "requests": {
            "name": "requests",
            "version": "2.28.2"
        },
        "certifi": {
            "name": "certifi",
            "version": "2022.12.7"
        },
        "charsetnormalizer": {
            "name": "charsetnormalizer",
            "version": "3.0.1"
        },
        "urllib3": {
            "name": "urllib3",
            "version": "1.26.14"
        },
        "typing": {
            "name": "typing",
            "version": "3.7.4.3"
        }
    },
    "affected_packages": {
        "numpy": {
            "name": "numpy",
            "version": "1.21.5",
            "found": "requirements.txt",
            "insecure_versions": [],
            "secure_versions": [],
            "latest_version_without_known_vulnerabilities": null,
            "latest_version": null,
            "more_info_url": "https://pyup.io"
        }
    },
    "announcements": [],
    "vulnerabilities": [
        {
            "vulnerability_id": "44717",
            "package_name": "numpy",
            "ignored": {},
            "ignored_reason": null,
            "ignored_expires": null,
            "vulnerable_spec": "<1.22.0",
            "all_vulnerable_specs": [
                "<1.22.0"
            ],
            "analyzed_version": "1.21.5",
            "advisory": "Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. \r\nNOTE: the vendor states that this reported code behavior is \"completely harmless.\"\r\nhttps://github.com/numpy/numpy/issues/18993",
            "is_transitive": false,
            "published_date": null,
            "fixed_versions": [],
            "closest_versions_without_known_vulnerabilities": [],
            "resources": [],
            "CVE": "CVE-2021-34141",
            "severity": null,
            "affected_versions": [],
            "more_info_url": "https://pyup.io/v/44717/f17"
        },
        {
            "vulnerability_id": "44716",
            "package_name": "numpy",
            "ignored": {},
            "ignored_reason": null,
            "ignored_expires": null,
            "vulnerable_spec": "<1.22.0",
            "all_vulnerable_specs": [
                "<1.22.0"
            ],
            "analyzed_version": "1.21.5",
            "advisory": "Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. \r\nNOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).\r\nhttps://github.com/numpy/numpy/issues/19000",
            "is_transitive": false,
            "published_date": null,
            "fixed_versions": [],
            "closest_versions_without_known_vulnerabilities": [],
            "resources": [],
            "CVE": "CVE-2021-41496",
            "severity": null,
            "affected_versions": [],
            "more_info_url": "https://pyup.io/v/44716/f17"
        },
        {
            "vulnerability_id": "44715",
            "package_name": "numpy",
            "ignored": {},
            "ignored_reason": null,
            "ignored_expires": null,
            "vulnerable_spec": "<1.22.2",
            "all_vulnerable_specs": [
                "<1.22.2"
            ],
            "analyzed_version": "1.21.5",
            "advisory": "Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. \r\nNOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.\r\nhttps://github.com/numpy/numpy/issues/19038",
            "is_transitive": false,
            "published_date": null,
            "fixed_versions": [],
            "closest_versions_without_known_vulnerabilities": [],
            "resources": [],
            "CVE": "CVE-2021-41495",
            "severity": null,
            "affected_versions": [],
            "more_info_url": "https://pyup.io/v/44715/f17"
        }
    ],
    "ignored_vulnerabilities": [],
    "remediations": {
        "numpy": {
            "current_version": "1.21.5",
            "vulnerabilities_found": 3,
            "recommended_version": null,
            "other_recommended_versions": [],
            "more_info_url": "https://pyup.io/?from=1.21.5"
        }
    }
}
